format: yamanifest
version: 1.0
---
work/atmosphere/yatm_70e2c46.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/yatm_70e2c46.exe
  hashes:
    binhash: 363c6bd6a6368548afe5e920f2ee43f3
    md5: 0bf97ac6aeb0e1efccc54aed252d6e5d
work/ice/cice_auscom_360x300_24p_edcfa6f_libaccessom2_d750b4b.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/cice_auscom_360x300_24p_edcfa6f_libaccessom2_d750b4b.exe
  hashes:
    binhash: 7cca1a89ede5c5196f2c9c0bb1f4bfde
    md5: 3bb0804115c5b37c7a4c66f2317c0f97
work/ocean/fms_ACCESS-OM_730f0bf_libaccessom2_d750b4b.x:
  fullpath: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_730f0bf_libaccessom2_d750b4b.x
  hashes:
    binhash: 106527763e934aacc49e5bc6a154d583
    md5: a7f3f29ca2d2a6b2431fe8949d0f6b6b
